---
- hosts: all
  become: true

- hosts: base
  become: true
  roles:
    - base

- hosts: centos_server
  become: true
  roles:
    - centos_server

- hosts: ubuntu_server
  become: true
  roles:
    - ubuntu_server
