---
- hosts: all
  become: true
  pre_tasks:

    - name: Install updates (CentOS)
      tags: always
      yum:
        name: '*'
        state: latest
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "CentOS"

    - name: Install updates (Ubuntu)
      tags: always
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "Ubuntu"

- hosts: centos_server
  become: true
  roles:
    - centos_server

- hosts: ubuntu_server
  become: true
  roles:
    - ubuntu_server
