- name: Install Chrony
  apt:
    name: chrony
    state: present

- name: Configure Chrony
  blockinfile:
    path: /etc/chrony/chrony.conf
    block: |
      server NTP_SERVER iburst
      allow 10.0.0.0/24
  become: yes

- name: Restart Chrony service
  service:
    name: chrony
    state: restarted
