---
# Network Time Protocol (NTP)
- name: Install Chrony on Ubuntu
  apt:
    name: chrony
    state: present

- name: Configure Chrony on Ubuntu
  replace:
    path: /etc/chrony/chrony.conf
    regexp: '^pool 2.debian.pool.ntp.org offline iburst'
    replace: '# pool 2.debian.pool.ntp.org offline iburst'
  become: yes

- name: Set controller as the NTP server on Ubuntu
  lineinfile:
    path: /etc/chrony/chrony.conf
    line: 'server controller iburst'
  become: yes

- name: Restart Chrony service on Ubuntu
  service:
    name: chrony
    state: restarted

# OpenStack Packages
- name: Add OpenStack Bobcat repository
  apt_repository:
    repo: 'deb http://archive.ubuntu.com/ubuntu/ focal-updates main'
    state: present
    filename: 'cloud-archive-bobcat'

- name: Add OpenStack Antelope repository
  apt_repository:
    repo: 'deb http://archive.ubuntu.com/ubuntu/ focal-updates main'
    state: present
    filename: 'cloud-archive-antelope'

- name: Add OpenStack Zed repository
  apt_repository:
    repo: 'deb http://archive.ubuntu.com/ubuntu/ focal-updates main'
    state: present
    filename: 'cloud-archive-zed'

- name: Add OpenStack Yoga repository
  apt_repository:
    repo: 'deb http://archive.ubuntu.com/ubuntu/ focal-updates main'
    state: present
    filename: 'cloud-archive-yoga'

- name: Install Nova Compute
  apt:
    name: nova-compute
    state: present

- name: Install OpenStack Client
  apt:
    name: python3-openstackclient
    state: present

# SQL Database
- name: Install MariaDB server and Python3 PyMySQL
  apt:
    name:
      - mariadb-server
      - python3-pymysql
    state: present

- name: Restart MariaDB
  service:
    name: mysql
    state: restarted

# Message Queue
- name: Install RabbitMQ server
  apt:
    name: rabbitmq-server
    state: present

- name: Add OpenStack user to RabbitMQ
  command: rabbitmqctl add_user openstack "{{ rabbitmq_password }}"
  args:
    creates: "/var/lib/rabbitmq/.erlang.cookie"
  vars:
    rabbitmq_password: 1234

# Memcached
- name: Install Memcached and Python3 Memcache
  apt:
    name:
      - memcached
      - python3-memcache
    state: present

- name: Edit Memcached configuration file
  lineinfile:
    path: /etc/memcached.conf
    line: '-l 10.0.0.11'
    backup: yes
  notify: Restart Memcached

- name: Restart Memcached
  service:
    name: memcached
    state: restarted

# Etcd
- name: Install Etcd
  apt:
    name: etcd
    state: present

- name: Edit Etcd configuration file
  lineinfile:
    path: /etc/default/etcd
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: '^ETCD_NAME=', line: 'ETCD_NAME="controller"' }
    - { regexp: '^ETCD_DATA_DIR=', line: 'ETCD_DATA_DIR="/var/lib/etcd"' }
    - { regexp: '^ETCD_INITIAL_CLUSTER_STATE=', line: 'ETCD_INITIAL_CLUSTER_STATE="new"' }
    - { regexp: '^ETCD_INITIAL_CLUSTER_TOKEN=', line: 'ETCD_INITIAL_CLUSTER_TOKEN="etcd-cluster-01"' }
    - { regexp: '^ETCD_INITIAL_CLUSTER=', line: 'ETCD_INITIAL_CLUSTER="controller=http://10.0.0.11:2380"' }
    - { regexp: '^ETCD_INITIAL_ADVERTISE_PEER_URLS=', line: 'ETCD_INITIAL_ADVERTISE_PEER_URLS="http://10.0.0.11:2380"' }
    - { regexp: '^ETCD_ADVERTISE_CLIENT_URLS=', line: 'ETCD_ADVERTISE_CLIENT_URLS="http://10.0.0.11:2379"' }
    - { regexp: '^ETCD_LISTEN_PEER_URLS=', line: 'ETCD_LISTEN_PEER_URLS="http://0.0.0.0:2380"' }
    - { regexp: '^ETCD_LISTEN_CLIENT_URLS=', line: 'ETCD_LISTEN_CLIENT_URLS="http://10.0.0.11:2379"' }
